# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

---
version: "2"

services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile.notebook
      # Uncomment the args line and one or more lines below it in order to use
      # a locally built copy of the development source code instead of the 
      # stable release set in the Dockerfile
      # args:
      #   DASHBOARDS: /src/jupyter_dashboards-0.6.0.dev0.tar.gz
      #   CMS /src/jupyter_cms-someversion.tar.gz
      #   DASHBOARDS_BUNDLERS /src/jupyter_dashboards_bundlers-someversion.tar.gz
      #   DECLARATIVE_WIDGETS /src/jupyter_declarativewidgets-someversion.tar.gz
    volumes:
      - /home/jovyan/work
    ports:
      - "8888:8888"
    depends_on:
      - dashboards
    links:
      - dashboards
    environment:
        DASHBOARD_REDIRECT_URL: http://{hostname}:4000/
        DASHBOARD_SERVER_URL: http://dashboards:3000/
        DASHBOARD_SERVER_AUTH_TOKEN: notebook_to_dashboard_secret

  dashboards:
    build:
      context: .
      dockerfile: Dockerfile.dashboards
      # Uncomment the lines below to use the local clone of dashboards server
      # instead of the stable npmjs.org release
      # args:
      #   DASHBOARDS_SERVER: /src
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      KERNEL_GATEWAY_URL: http://kernel_gateway:8888
      AUTH_TOKEN: notebook_to_dashboard_secret
      USERNAME: demo
      PASSWORD: demo

  kernel_gateway:
    build:
      context: .
      dockerfile: Dockerfile.kernel
      # Uncomment the lines below to use a locally built copy of the development
      # source code for declarative widgets. NOTE: This MUST match the version
      # set for notebook above if you uncomment it
      # args:
      #   DECLARATIVE_WIDGETS /src/jupyter_declarativewidgets-someversion.tar.gz
    volumes_from:
      - notebook
    environment:
      KG_ALLOW_ORIGIN: '*'
